/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jwo_landserf_process_gps_garmin_GarminUSB */

#ifndef _Included_jwo_landserf_process_gps_garmin_GarminUSB
#define _Included_jwo_landserf_process_gps_garmin_GarminUSB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jwo_landserf_process_gps_garmin_GarminUSB
 * Method:    initGPS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwo_landserf_process_gps_garmin_GarminUSB_initGPS
  (JNIEnv *, jobject);

/*
 * Class:     jwo_landserf_process_gps_garmin_GarminUSB
 * Method:    sendPacket
 * Signature: (BS[B)I
 */
JNIEXPORT jint JNICALL Java_jwo_landserf_process_gps_garmin_GarminUSB_sendPacket
  (JNIEnv *, jobject, jbyte, jshort, jbyteArray);

/*
 * Class:     jwo_landserf_process_gps_garmin_GarminUSB
 * Method:    getPacket
 * Signature: ([I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jwo_landserf_process_gps_garmin_GarminUSB_getPacket
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
