PAR.unmanaged.filename <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/condModel_unmanaged_curve.txt"
cond.model.root.filename <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/condMap"
PAR.management.cost.per.pixel <- 15.0
OPT.partial.offsets.allowed <- TRUE
zonation.threshold <- 0.8
PAR.grassland.max.cond.score <- 0.75
non.habitat.indicator <- 0
offsettingGlobalsTableName <- "OFFSETTING_GLOBALS"
OPTsampleMelbCostsFromLogNormDist <- FALSE
reserved.planning.units.filename.base <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/reservedPlanningUnits"
OPT.reserve.parcels.based.on.budget <- FALSE
DEBUG <- FALSE
OPT.leak.offsets.outside.study.area <- FALSE
loss.model.root.filename <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/lossModel"
OPT.private.offset.multiplier <- 1
OPT.strategic.offset.multiplier <- 1
Debug.Num.of.PUs.to.test.with <- 10
OPT.use.offsetting.in.loss.model <- FALSE
usePreviousZonationResult <- TRUE
use.run.number.as.seed <- TRUE
OPT.probResExpiringPerTimeStep <- 0
PAR.managed.below.thresh.filename <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/condModel_below_thresh_curve.txt"
OPT.probManExpiringPerTimeStep <- 0
reserveSelectionMethod <- "ZONATION"
PAR.managed.above.thresh.filename <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/condModel_above_thresh_curve.txt"
reserved.pid.list.filename <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/reserved.pid.list.txt"
PAR.pus.in.dev.pool <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/PUs_IN_DEV_POOL.txt"
OPT.specify.development.pool.with.map <- TRUE
current.time.step <- 20
PAR.pus.lost.per.timestep <- 0
OPT.use.smoothing.in.grassland.cond.model <- FALSE
reserve.map.name.base <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/zreserve.map"
start_point <- 1
PAR.reserve.duration <- 10000
numTimeSteps <- 4
pixel.size <- 50
PAR.offset.pool.map.filename <- "UNDEFINED"
rows <- 782
PAR.management.duration <- 9999
planning.units.filename <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/planning.units.uid_20ha.txt"
OPT.offset.leakage.prob <- 0.2
OPT.offset.pool.option <- "UNDEFINED"
step.interval <- 5
Debug.Test.With.20.PUs <- FALSE
offsettingTestingInfoTableName <- "offsettingTestingInfo"
PAR.fixed.val.for.smoothing <- 0.12
planning.units.filename.base <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/planning.units.uid_20ha"
offsettingWorkingVarsTableName <- "OFFSETTING_WORKING_VARS"
OPT.specify.offset.pool.with.map <- FALSE
CondDBname <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/conddb.dbms"
OPT.use.raster.maps.for.input.and.output <- TRUE
PAR.time.steps.filename <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/condModel_timesteps.txt"
OPT.cost.scenario <- 6
test_dev_and_offsetting_loop <- TRUE
OPT.smoothing.option <- 2
LandscapeCondTableName <- "landscapeCondition"
DebugSaveLossModelOutFiles <- FALSE
PAR.grassland.variability.std.dev <- 0.02
PUinformationDBname <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/PUdb.dbms"
PAR.pus.in.offset.pool <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/PUs_IN_OFFSET_POOL.txt"
PAR.grassland.threshold.value <- 0.35
PAR.grassland.min.cond.score <- 0.1
OPT.unmanaged.is.stable <- FALSE
PAR.zonation.prop.of.patch.overlap <- 1
globalDBdriver <- "SQLite"
Debug.Test.With.given.num.of.PUs <- FALSE
PAR.offset.pool.map.filename.random <- "offset_pool_mask_random.txt"
PAR.prob.of.crossing.thresh <- 0.0005
cols <- 832
dbmsFunctionsRFileName <- "dbms.functions.variables.melb.grassland.R"
PUcondTableName <- "PUcond"
PAR.prop.pixels.in.PU.to.reserve <- 0.7
managed.planning.units.filename.base <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/managedPlanningUnits"
master.habitat.map.zo1.base.filename <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/hab.map.master.zo1"
pu.reserve.info.file <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/puReserveInfo.txt"
PAR.zonation.select.partial.patches <- TRUE
cost.map.base.filename <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/costMap"
unreserved.pid.list.filename <- "/Users/ascelin/tzar/outputdata/Melb_grassland/default_runset/43_Do_nothing.inprogress/unreserved.pid.list.txt"
staticPUinfoTableName <- "staticPUinfo"
dynamicPUinfoTableName <- "dynamicPUinfo"
PAR.Zonation.reserve.map <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/zonation_output.rank.txt"
runID <- 43
PAR.development.pool.map.filename <- "/Users/ascelin/analysis/src/rdv-framework/projects/melb-grassland/input_data/dev_pool_mask.txt"
PAR.offset.pool.map.filename.strategic <- "offset_pool_mask_strategic.txt"
OPT.do.strategic.offsetting <- FALSE
