project_name: biodivprobgen
runner_class: RRunner

#####
#####  2014 12 11 - BTL
#####  Note that all variables containing the word "group" have been 
#####  changed to use the word "group" instead.
#####

    #  Cloned from project.yaml in example-R-pop-model.
    
base_params:

    seed: 111

            #  1 - num_groups = tot cost, so increase n to reduce cost
            #  What is a reasonable range?
            #  Xu uses ???
            #
            #      num_nodes_per_group = integerize (n__num_groups ^ alpha__)
    n__num_groups: 20
#    n__num_groups: 5
    
            #  Drives the number of PUs per group and so, tot num PUs
            #  What is a reasonable range?
            #  Xu uses ???
            #
            #  Increase alpha to increase num of PUs.
            #      tot_num_nodes = n__num_groups * num_nodes_per_group
    alpha__: 0.25
#    alpha__: 0.8

            #  p and r drive num of spp (increase p to increase num of spp)
            #  What is a reasonable range?
            #  Xu uses ???
            #
            #     target_num_links_between_2_groups_per_round = 
            #         integerize (p__prop_of_links_between_groups * num_nodes_per_group)          
            #     num_rounds_of_linking_between_groups = integerize (r__density * n__num_groups * log (n__num_groups))            
            #     max_possible_num_links_between_groups = 
            #         integerize (target_num_links_between_2_groups_per_round * num_rounds_of_linking_between_groups)
            #     max_possible_tot_num_links = integerize (tot_num_links_inside_groups + max_possible_num_links_between_groups)

    p__prop_of_links_between_groups: 0.8
#    p__prop_of_links_between_groups: 0.5
    r__density: 0.8
#    r__density: 0.5



#    n__num_groups: 12
#    alpha__: 1.5
#    p__prop_of_links_between_groups: 0.3
#    r__density: 0.8


        #  2014 12 11 - BTL - Added.
    num_independent_nodes_per_group: 1
    integerize_string: "round"
    base_for_target_num_links_between_2_groups_per_round: "num_nodes_per_group"
#    base_for_target_num_links_between_2_groups_per_round: "num_dependent_nodes_per_group"
#    at_least_1_for_target_num_links_between_2_groups_per_round: TRUE
    at_least_1_for_target_num_links_between_2_groups_per_round: FALSE


    
    run_id: $$run_id$$
    
    marxan_input_parameters_file_name: "/Users/bill/D/Marxan/input.dat"
    marxan_num_reps: 100
    marxan_num_iterations: "2000000"

#    marxan_spf_const: 100
    marxan_spf_const: 10
    
        # Outputs
        
    summary_filename: $$output_path$$prob_diff_results.csv
#    output.plot : $$output_path$$poptraj
#    output.dump : $$output_path$$projtraj.R

