project_name: biodivprobgen
runner_class: RRunner

#####
#####  2014 12 11 - BTL
#####  Note that all variables containing the word "group" have been 
#####  changed to use the word "group" instead.
#####

    #  Cloned from project.yaml in example-R-pop-model.
    
base_params:


        #  BTL - 2014 12 28
        #  This variable captures the tzar output path to hand it to the 
        #  tzar emulation code.  It is absolutely necessary for the current 
        #  version of emulation, but might go away in the future if River 
        #  adds emulation directly inside of tzar with a "dry run" command.
        #  Note that I had forgotten to add this variable to any of the 
        #  project.yaml files used in biodivprobgen runs before today, so 
        #  you need to add it back into any of those that you re-use under  
        #  emulation.  That's not so likely though, since they're generally 
        #  doing zillions of runs and you don't generally do that under 
        #  emulation.
    fullOutputDirWithSlash: $$output_path$$

#    runset_name: $$runset$$    #  Looks like there is no access to runset.

    max_allowed_possible_tot_num_links: 2000

    seed: 111

    use_unif_rand_n__num_groups: FALSE
    n__num_groups: 29
    
    use_unif_rand_alpha__: FALSE
    alpha__: 0.169201
    
    use_unif_rand_p__prop_of_links_between_groups: FALSE
    p__prop_of_links_between_groups: 0.1919268
    
    use_unif_rand_r__density: FALSE
    r__density: 4.031895


        #  2014 12 11 - BTL - Added.
    num_independent_nodes_per_group: 1
    integerize_string: "round"
    base_for_target_num_links_between_2_groups_per_round: "num_nodes_per_group"
#    base_for_target_num_links_between_2_groups_per_round: "num_dependent_nodes_per_group"
#    at_least_1_for_target_num_links_between_2_groups_per_round: TRUE
    at_least_1_for_target_num_links_between_2_groups_per_round: FALSE


    
    run_id: $$run_id$$
    
    marxan_input_parameters_file_name: "/Users/bill/D/Marxan/input.dat"
    marxan_num_reps: 100
    marxan_num_iterations: "2000000"

#    marxan_spf_const: 100
    marxan_spf_const: 10
    
        # Outputs

    timepoints_filename: $$output_path$$timepoints.csv

    summary_filename: $$output_path$$prob_diff_results.csv
    summary_without_run_id_filename: $$output_path$$prob_diff_results_with_0_run_id.csv
#    output.plot : $$output_path$$poptraj
#    output.dump : $$output_path$$projtraj.R

#repetitions:
#    generators:
#        - key: seed
#          generator_type: linear_step
#          start: 251
#          step_size: 1
#          count: 100    #  500

#        - key: p__prop_of_links_between_cliques
#          generator_type: linear_step
#          start: 0.26
#          step_size: 0.01
#          count: 6

#        - key: r__density
#          generator_type: linear_step
#          start: 6.0
#          step_size: 0.5
#          count: 2

#        - key: alpha__
#          generator_type: linear_step
#          start: 0.20
#          step_size: 0.25
#          count: 1

#        - key: n__num_groups
#          generator_type: linear_step
#          start: 40
#          step_size: 5
#          count: 1          
          
          
#concatenate:
#  heading_row: true
#  input_filename: prob_diff_results.csv
#  output_filename: all_results_prob_diff.csv

