#===============================================================================

                            #  timepoints.R

#  Code to track and print the elapsed time since a starting point and 
#  since the last chunk of code started.

#===============================================================================

#  History:

#  2015 01 08 - BTL
#       Created initial code embedded in generateSetCoverProblem.R
#
#  2015 01 09 - BTL
#       Extracted into separate file.  

#===============================================================================

    #  Values derived from the list generated by tzar (or anywhere else that 
    #  generates a "parameters" object with these attributes).  
    #  If you're using this inside of tzar, this has to come after tzar 
    #  has built the object.  Under tzar emulation, that means that this 
    #  has to come after the emulator code runs.
    #  If you're using this code outside of tzar altogether, then you can 
    #  either create a parameters object with these attributes or just 
    #  replace the assignments here with something more appropriate to 
    #  your situation.

run_ID = parameters$run_id
runset_name = parameters$runset_name

    #  Could be specified somewhere else as well, e.g., in the tzar parameters 
    #  file.
timepoints_df_default_length = 20

#===============================================================================

    #  Print a label message followed by the total elapsed time for the 
    #  run so far and then the elapsed time for the previous section, i.e., 
    #  for the section since the last call to this routine.
    #  This is useful for marking progress of long runs and for recording 
    #  how long different parts of the run take.
    #
    #  Usage:
    #       prev_time = timepoint (start_time, prev_time, string_to_print)

timepoint = function (timepoints_df, 
                      cur_timepoint_name, 
                      string_to_print)
    {
    cur_timepoint_num <<- cur_timepoint_num + 1    #  Note global assignment...
    cat ("\n\nTP", cur_timepoint_num, ":", string_to_print, "\n\n")
    
    #----------
    
    cur_time = proc.time()
    
    prev_chunk_elapsed_time = cur_time - prev_time
    cat ("Elapsed time for previous chunk:\n")
    print (prev_chunk_elapsed_time)

    total_elapsed_time = cur_time - start_time
    cat ("Total elapsed time:\n")
    print (total_elapsed_time)

    cat ("\n")

    #----------
    
    timepoints_df [cur_timepoint_num, "timepoint_num"] = 
        cur_timepoint_num
    timepoints_df [cur_timepoint_num, "timepoint_name"] = 
        cur_timepoint_name
    
    timepoints_df [cur_timepoint_num, "prev_chunk_elapsed_user"] = 
        prev_chunk_elapsed_time [1]    
    timepoints_df [cur_timepoint_num, "tot_elapsed_user"] = 
        total_elapsed_time [1]
    
    timepoints_df [cur_timepoint_num, "prev_chunk_elapsed_system"] = 
        prev_chunk_elapsed_time [2]
    timepoints_df [cur_timepoint_num, "tot_elapsed_system"] = 
        total_elapsed_time [2]
    
    timepoints_df [cur_timepoint_num, "cur_time_user"] = 
        cur_time [1]
    timepoints_df [cur_timepoint_num, "cur_time_system"] = 
        cur_time [2]

    #----------
    
    prev_time <<- cur_time    #  Note global assignment...

    return (timepoints_df)
    }

#-------------------------------------------------------------------------------

timepoints_df = 
    data.frame (timepoint_num = 1:timepoints_df_default_length, 
                timepoint_name = rep (NA, timepoints_df_default_length),
                prev_chunk_elapsed_user = rep (NA, timepoints_df_default_length),
                tot_elapsed_user = rep (NA, timepoints_df_default_length),
                prev_chunk_elapsed_system = rep (NA, timepoints_df_default_length),
                tot_elapsed_system = rep (NA, timepoints_df_default_length),
                cur_time_user = rep (NA, timepoints_df_default_length),
                cur_time_system = rep (NA, timepoints_df_default_length),
                run_ID = run_ID, 
                runset_name = runset_name
                )

    #  First time, intialization.
cur_timepoint_num = 0
prev_time = start_time = proc.time()

    #  Each time...

timepoints_df = timepoint (timepoints_df, "start", "Run start...")

#===============================================================================

