project_name: USG-analysis
runner_class: RRunner

libraries:
    -  name: zonation-dat-files
       repo_type: svn
       url: https://rdv-framework.googlecode.com/svn/trunk/projects/usg/zsettings
       revision: 504

base_params:

    #If this is true, it will run the R script without running zonation (most of the time this will be false once the R scripts are good to go)
    do.dry.run: False

    # Variables for running zonation 
    #location of zonation run file
    z.executable: /usr/local/bin/zig3
    
    #location of the .dat file
    z.settings.file: $$library_path(zonation-dat-files)$$/old_z_settings_S1.dat 

    #location of the .spp file    (this file is generated dynamically by R by listing files in input directory)
    z.spp.list.filename: $$output_path$$zonation_spp_list.spp

    # new parameter for the weights vector file
    #z.settings.file: $$library_path(zonation-dat-files)$$/equal_weights_filename.txt 

    
    #location of the output files (don't need to change this)
    z.output.file: $$output_path$$zoutput.txt

    #last numbers on the zonation command line system call (we won't change these for now)
    z.other.cmd.line.args: 0.0 0 1.0 1

    # Note: we are assuming that the input spp maps are already on the
    # machine where this is running as there are many gigs of input
    # data

    z.input.data.dir: /mnt/data/all_input_maps
    
    #NOTE: THIS IS THE TEST DIRECTORY:
    #z.input.data.dir: /home/ubuntu/usg_data/spp_maps

scenarios:
    #- name: S1 base
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_base_scen1.dat
    #- name: S2 current small test
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_mask_scen2current.dat
    #      z.input.data.dir: /home/ubuntu/usg_data/spp_maps
    #- name: S2 current
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_mask_scen2current.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S5 new mask eyre
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_mask_scen5.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S6 new condition eyre
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_condition_scen6.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S7 new mask eyre yorke
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_mask_scen7.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S8 new condition eyre yorke
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_condition_scen8.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S9 new mask eyre yorke braemar
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_mask_scen9.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S10 new condition eyre yorke braemar
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_condition_scen10.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S11 new mask all ports
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_mask_scen11.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    #- name: S12 new condition all ports
    #  parameters:
    #      z.settings.file: $$library_path(zonation-dat-files)$$/set_condition_scen12.dat
    #      z.input.data.dir: /mnt/data/all_input_maps
    - name: S2 current
      parameters:
          z.settings.file: $$library_path(zonation-dat-files)$$/currinfnopas.dat
          z.input.data.dir: /mnt/data/all_input_maps