project_name: USG-analysis
runner_class: RRunner

base_params:

    test.variable.1: 123
    test.variable.2: 456


    # Zonation 
    z.executable: /usr/local/bin/zig3
    z.settings.file: /home/ubuntu/usg_zigtest/input_final/setMarch11_mask.dat
    z.spp.file: /home/ubuntu/usg_zigtest/input_final/splist.spp
    z.output.file: output.txt
    z.other.cmd.line.args: 0.0 0 1.0 1


scenarios:
    - name: Example scenario 1
      parameters:
    # - name: Example scenario 2
    #   parameters:
    #       test.variable.1: 789

