#===============================================================================

project_name: g2
runner_class: RRunner

#===============================================================================

libraries:
    -  name: maxentLibrary
       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/maxent.zip

#---------------------------------------

    -  name: zonationLibraryLinux
       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/zonationLinux.zip
#       url: http://glass.eres.rmit.edu.au/tzar_input/g2/zig2.zip

#---------------------------------------

    -  name: zonationLibraryWindows
       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/zonationWindows.zip
#       url: http://glass.eres.rmit.edu.au/tzar_input/g2/zig2.zip

#---------------------------------------

    -  name: envDataLayersLibrary

#       repo_type: local_file
#       url: file:///Users/Bill/D/Data/MattsVicTestLandscape/MtBuffaloEnvVars_Originals

       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/MtBuffaloEnvVars_Originals.zip

#---------------------------------------

    -  name: clusterLibrary

#       repo_type: local_file
#       url: file:///Users/Bill/D/Data/MattsVicTestLandscape/MtBuffaloSupervisedClusterLayers

       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/MtBuffaloSupervisedClusterLayers.zip

#---------------------------------------

    -  name: samplingBiasLibrary

#       repo_type: local_file
#       url: file:///Users/Bill/D/Data/MattsVicTestLandscape/MtBuffaloSamplingBiasVars

       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/MtBuffaloSamplingBiasVars.zip

#===============================================================================

base_params:
    warningLevel: 2         #  tells R whether to show warnings or quit, etc.

    fullTzarExpOutputDirRootWithSlash: $$output_path$$

#-------------------------------------------------------------------------------

        #----------------------------------------------------------------
        #  File and path names that have to be specified separately for
        #  each OS because of directory separator issues.
        #----------------------------------------------------------------

#---------------------------------------

    userPath.mac:            "/Users/Bill"
    userPath.linux:          "/Users/Bill"    #  what is this supposed to be on linux?

    userPath.windows.vmware: "Z:\\Bill"    #  \\\\vmware-host\\Shared Folders\\Bill"

#---------------------------------------

    rdvRootDir.mac:            "D/rdv-framework"
    rdvRootDir.linux:          "D/rdv-framework"    #  what is this supposed to be on linux?

    rdvRootDir.windows.vmware: "D\\rdv-framework"

#---------------------------------------

    envLayersSrcDir.mac:            "$$library_path(envDataLayersLibrary)$$/LowerLeft_r256c256/UpperRight_r128c128"
    envLayersSrcDir.linux:          "$$library_path(envDataLayersLibrary)$$/LowerLeft_r256c256/UpperRight_r128c128"

    envLayersSrcDir.windows.vmware: "$$library_path(envDataLayersLibrary)$$\\LowerLeft_r256c256\\UpperRight_r128c128"

#---------------------------------------

    clusterFilePath.mac: "$$library_path(clusterLibrary)$$/LowerLeft_r256c256/UpperRight_r128c128/"
    clusterFilePath.linux: "$$library_path(clusterLibrary)$$/LowerLeft_r256c256/UpperRight_r128c128/"

    clusterFilePath.windows.vmware: "$$library_path(clusterLibrary)$$\\LowerLeft_r256c256\\UpperRight_r128c128\\"

#---------------------------------------

    maxentFullPathName.mac:            "$$library_path(maxentLibrary)$$/maxent.jar"
    maxentFullPathName.linux:          "$$library_path(maxentLibrary)$$/maxent.jar"

    maxentFullPathName.windows.vmware: "$$library_path(maxentLibrary)$$\\maxent.jar"

#---------------------------------------

    fullPathToZonationExe.mac:            "$$library_path(zonationLibraryWindows)$$/zig3.exe"
    fullPathToZonationExe.linux:          "$$library_path(zonationLibraryLinux)$$/zig3.exe"

    fullPathToZonationExe.windows.vmware: "$$library_path(zonationLibraryWindows)$$\\zig3.exe"

#---------------------------------------

    fullPathToZonationParameterFile.mac:            "$$library_path(zonationLibraryWindows)$$/Z_parameter_settings.dat"
    fullPathToZonationParameterFile.linux:          "$$library_path(zonationLibraryLinux)$$/Z_parameter_settings.dat"

    fullPathToZonationParameterFile.windows.vmware: "$$library_path(zonationLibraryWindows)$$\\Z_parameter_settings.dat"

#---------------------------------------

        #  All of these are identical, so it looks unnecessary to split them
        #  up by OS.
        #  Commenting out - BTL - 2014 03 28.

#    fullPathToZonationFilesDir.mac: $$output_path$$Zonation
#    fullPathToZonationFilesDir.windows.vmware: $$output_path$$Zonation
#    fullPathToZonationFilesDir.linux: $$output_path$$Zonation

    fullPathToZonationFilesDir: $$output_path$$Zonation

#-------------------------------------------------------------------------------

    envLayersWorkingDirName: "InputEnvLayers"

    sppFilePrefix: "spp"

    smoothSuitabilitiesWithGaussian: TRUE
    gaussianSuitabilitySmoothingMean: 0
    gaussianSuitabilitySmoothingSD: 1

    scaleInputs: TRUE  #  DO NOT CHANGE THIS VALUE FOR NOW.  SEE COMMENT in original code.
    dataSrc: "mattData"    #  Should become a guppy option...

    numSpp: NA

    randomSeed: 17

    imgFileType: "asc"
    numNonEnvDataCols: 0

    clusterFileNameStem: "env_clusters"

    trueProbDistSppFilenameBase: "true.prob.dist.spp."

    trueProbDistFilePrefix: "true.prob.dist"

    useRandomNumTruePresForEachSpp: TRUE    #  variables$PAR.use.random.num.true.presences
    minTruePresFracOfLandscape:  0.3    #  0.0002    #  0.002    #  variables$PAR.min.true.presence.fraction.of.landscape
    maxTruePresFracOfLandscape:  0.6    #  0.002     #  0.2      # variables$PAR.max.true.presence.fraction.of.landscape
    numTruePresForEachSpp_string: "50,100,75"    #  variables$PAR.num.true.presences

    PARuseAllSamples: FALSE

    doMaxentReplicates: FALSE
    maxentReplicateType: "crossvalidate"
    numMaxentReplicates: 5

    numProcessors: 1
    verboseMaxent: TRUE


    showRawErrorInDist: TRUE
    showAbsErrorInDist:  TRUE
    showPercentErrorInDist:  TRUE
    showAbsPercentErrorInDist:  TRUE
    showTruncatedPercentErrImg:  TRUE
    showHeatmap: FALSE

    useOldMaxentOutputForInput: FALSE
    writeToFile: TRUE
    useDrawImage: FALSE


    asciiImgFileNameRoots:
        - "aniso_heat"
        - "evap_jan"
        - "evap_jul"
        - "insolation"
        - "max_temp"
        - "min_temp"
        - "modis_evi"
        - "modis_mir"
        - "ndmi"
        - "pottassium"
        - "raindays_jan"
        - "raindays_jul"
        - "rainfall_jan"
        - "rainfall_jul"
        - "thorium"
        - "twi_topocrop"
        - "vert_major"
        - "vert_minor"
        - "vert_saline"
        - "vis_sky"


    envLayerWeights:    #  not used yet.  Just remembering what Matt suggested.
        "aniso_heat": "randomIn0-1"
        "evap_jan": 0.5
        "evap_jul": 0.5
        "insolation": "randomIn0-1"
        "max_temp": 0.5
        "min_temp": 0.5
        "modis_evi": 0.5
        "modis_mir": 0.5
        "ndmi": 0.5
        "pottassium": "randomIn0-1"
        "raindays_jan": 0.5
        "raindays_jul": 0.5
        "rainfall_jan": 0.5
        "rainfall_jul": 0.5
        "thorium": "randomIn0-1"
        "twi_topocrop": "randomIn0-1"
        "vert_major": "randomIn0-1"
        "vert_minor": "randomIn0-1"
        "vert_saline": "randomIn0-1"
        "vis_sky": "randomIn0-1"


        # Zonation

    runZonation: TRUE

    closeZonationWindowOnCompletion: TRUE

    zonationAppSppListFilename: "zonation_app_spp_list.dat"
    zonationAppOutputFilename: "zonation_app_output"

    zonationCorSppListFilename: "zonation_cor_spp_list.dat"
    zonationCorOutputFilename: "zonation_cor_output"


    numSppInReserveSelection: 28    ##  100    #  No reserve selection yet.


scenarios:
#    - name: Full512
#      parameters:
#          envLayersSrcDir.windows.vmware: "$$library_path(envDataLayersLibrary)$$"
#          clusterFilePath.windows.vmware: "$$library_path(clusterLibrary)$$\\"

    - name: LowerRight256
      parameters:
          envLayersSrcDir.windows.vmware: "$$library_path(envDataLayersLibrary)$$\\LowerRight_r256c256"
          clusterFilePath.windows.vmware: "$$library_path(clusterLibrary)$$\\LowerRight_r256c256\\"
##    - name: UpperRight256
##      parameters:
##          envLayersSrcDir.windows.vmware: "$$library_path(envDataLayersLibrary)$$\\UpperRight_r256c256"
##          clusterFilePath.windows.vmware: "$$library_path(clusterLibrary)$$\\UpperRight_r256c256\\"
##    - name: LowerLeft256
##      parameters:
##          envLayersSrcDir.windows.vmware: "$$library_path(envDataLayersLibrary)$$\\LowerLeft_r256c256"
##          clusterFilePath.windows.vmware: "$$library_path(clusterLibrary)$$\\LowerLeft_r256c256\\"
##    - name: UpperLeft256
##      parameters:
##          envLayersSrcDir.windows.vmware: "$$library_path(envDataLayersLibrary)$$\\UpperLeft_r256c256"
##          clusterFilePath.windows.vmware: "$$library_path(clusterLibrary)$$\\UpperLeft_r256c256\\"

#---------------------------------------

# Note that this file does all repetitions on scen 1, then on scen 2 etc...
# Note that also the original value of the variable is not used.

#repetitions:
###    static_repetitions:
###      - test.variable.2: 777
#
###      - test.variable.2: 888
#
#    generators:
#      - key: randomSeed
#        generator_type: linear_step
#        start: 80
#        step_size: 1
#        count: 1
#
###      - key: test.variable.4
###        generator_type: normal_distribution
###        mean: 5
###        std_dev: 1
###        count: 2


#===============================================================================

