project_name: g2
runner_class: RRunner

#-------------------------------------------------------------------------------

libraries:
    -  name: maxentLibrary
       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/maxent.zip

    -  name: zonationLibrary
       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/g2/zonation.zip
 
#-------------------------------------------------------------------------------

base_params:
    warningLevel: 2         #  tells R whether to show warnings or quit, etc.

    fullTzarExpOutputDirRootWithSlash: $$output_path$$

#-------------------------------------------------------------------------------

        #----------------------------------------------------------------
        #  File and path names that have to be specified separately for
        #  each OS because of directory separator issues.
        #----------------------------------------------------------------

#---------------------------------------

    userPath.mac: "/Users/Bill"
    userPath.windows.vmware: "Z:\\Bill"    #  \\\\vmware-host\\Shared Folders\\Bill"
    userPath.linux: "/Users/Bill"

#---------------------------------------

    rdvRootDir.mac: "D/rdv-framework"
    rdvRootDir.windows.vmware: "D\\rdv-framework"
    rdvRootDir.linux: "D/rdv-framework"

#---------------------------------------

    envLayersSrcDir.mac: "D/Data/MattsVicTestLandscape/MtBuffaloEnvVars_Originals/LowerLeft_r256c256/UpperRight_r128c128/"
    envLayersSrcDir.windows.vmware: "D\\Data\\MattsVicTestLandscape\\MtBuffaloEnvVars_Originals\\LowerLeft_r256c256\\UpperRight_r128c128\\"
    envLayersSrcDir.linux: "D/Data/MattsVicTestLandscape/MtBuffaloEnvVars_Originals/LowerLeft_r256c256/UpperRight_r128c128/"

#---------------------------------------

    clusterFilePath.mac: "D/Data/MattsVicTestLandscape/MtBuffaloSupervisedClusterLayers/LowerLeft_r256c256/UpperRight_r128c128/"
    clusterFilePath.windows.vmware: "D\\Data\\MattsVicTestLandscape\\MtBuffaloSupervisedClusterLayers\\LowerLeft_r256c256\\UpperRight_r128c128\\"
    clusterFilePath.linux: "D/Data/MattsVicTestLandscape/MtBuffaloSupervisedClusterLayers/LowerLeft_r256c256/UpperRight_r128c128/"

#---------------------------------------

#    maxentFullPathName.mac: "D/rdv-framework/lib/maxent/maxent.jar"
    maxentFullPathName.mac: "$$library_path(maxentLibrary)$$/maxent.jar"

#    maxentFullPathName.windows.vmware: "D\\rdv-framework\\lib\\maxent\\maxent.jar"
    maxentFullPathName.windows.vmware: "$$library_path(maxentLibrary)$$\\maxent.jar"
    maxentFullPathName.linux: "D/rdv-framework/lib/maxent/maxent.jar"

#---------------------------------------

#    fullPathToZonationExe.mac: "D/rdv-framework/lib/zonation/zig3.exe"
    fullPathToZonationExe.mac: "$$library_path(zonationLibrary)$$/zig3.exe"

#    fullPathToZonationExe.windows.vmware: "D\\rdv-framework\\lib\\zonation\\zig3.exe"
    fullPathToZonationExe.windows.vmware: "$$library_path(zonationLibrary)$$\\zig3.exe"

    fullPathToZonationExe.linux: "D/rdv-framework/lib/zonation/zig3.exe"

#---------------------------------------

#    fullPathToZonationParameterFile.mac: "D/rdv-framework/lib/zonation/Z_parameter_settings.dat"
    fullPathToZonationParameterFile.mac: "$$library_path(zonationLibrary)$$/Z_parameter_settings.dat"

#    fullPathToZonationParameterFile.windows.vmware: "D\\rdv-framework\\lib\\zonation\\Z_parameter_settings.dat"
    fullPathToZonationParameterFile.windows.vmware: "$$library_path(zonationLibrary)$$\\Z_parameter_settings.dat"
    fullPathToZonationParameterFile.linux: "D/rdv-framework/lib/zonation/Z_parameter_settings.dat"

#---------------------------------------

    fullPathToZonationFilesDir.mac: $$output_path$$Zonation
    fullPathToZonationFilesDir.windows.vmware: $$output_path$$Zonation
    fullPathToZonationFilesDir.linux: $$output_path$$Zonation

#-------------------------------------------------------------------------------

    envLayersWorkingDirName: "InputEnvLayers"

    sppFilePrefix: "spp"

    smoothSuitabilitiesWithGaussian: TRUE
    gaussianSuitabilitySmoothingMean: 0
    gaussianSuitabilitySmoothingSD: 1

    scaleInputs: TRUE  #  DO NOT CHANGE THIS VALUE FOR NOW.  SEE COMMENT in original code.
    dataSrc: "mattData"    #  Should become a guppy option...

    numSpp: NA

    randomSeed: 17

    imgFileType: "asc"
    numNonEnvDataCols: 0

    clusterFileNameStem: "env_clusters"

    trueProbDistSppFilenameBase: "true.prob.dist.spp."

    trueProbDistFilePrefix: "true.prob.dist"

    useRandomNumTruePresForEachSpp: TRUE    #  variables$PAR.use.random.num.true.presences
    minTruePresFracOfLandscape: 0.0002    #  0.002    #  variables$PAR.min.true.presence.fraction.of.landscape
    maxTruePresFracOfLandscape: 0.002     #  0.2      # variables$PAR.max.true.presence.fraction.of.landscape
    numTruePresForEachSpp_string: "50,100,75"    #  variables$PAR.num.true.presences

    PARuseAllSamples: FALSE

    doMaxentReplicates: FALSE
    maxentReplicateType: "crossvalidate"
    numMaxentReplicates: 5

    numProcessors: 1
    verboseMaxent: TRUE


    showRawErrorInDist: TRUE
    showAbsErrorInDist:  TRUE
    showPercentErrorInDist:  TRUE
    showAbsPercentErrorInDist:  TRUE
    showTruncatedPercentErrImg:  TRUE
    showHeatmap: FALSE

    useOldMaxentOutputForInput: FALSE
    writeToFile: TRUE
    useDrawImage: FALSE


    asciiImgFileNameRoots:
        - "aniso_heat"
        - "evap_jan"
        - "evap_jul"
        - "insolation"
        - "max_temp"
        - "min_temp"
        - "modis_evi"
        - "modis_mir"
        - "ndmi"
        - "pottassium"
        - "raindays_jan"
        - "raindays_jul"
        - "rainfall_jan"
        - "rainfall_jul"
        - "thorium"
        - "twi_topocrop"
        - "vert_major"
        - "vert_minor"
        - "vert_saline"
        - "vis_sky"


    envLayerWeights:
        "aniso_heat": "randomIn0-1"
        "evap_jan": 0.5
        "evap_jul": 0.5
        "insolation": "randomIn0-1"
        "max_temp": 0.5
        "min_temp": 0.5
        "modis_evi": 0.5
        "modis_mir": 0.5
        "ndmi": 0.5
        "pottassium": "randomIn0-1"
        "raindays_jan": 0.5
        "raindays_jul": 0.5
        "rainfall_jan": 0.5
        "rainfall_jul": 0.5
        "thorium": "randomIn0-1"
        "twi_topocrop": "randomIn0-1"
        "vert_major": "randomIn0-1"
        "vert_minor": "randomIn0-1"
        "vert_saline": "randomIn0-1"
        "vis_sky": "randomIn0-1"


        # Zonation

    runZonation: TRUE

    closeZonationWindowOnCompletion: TRUE

    zonationAppSppListFilename: "zonation_app_spp_list.dat"
    zonationAppOutputFilename: "zonation_app_output"

    zonationCorSppListFilename: "zonation_cor_spp_list.dat"
    zonationCorOutputFilename: "zonation_cor_output"


    numSppInReserveSelection: 11  #  28    ##  100    #  No reserve selection yet.

