project_name: g2
runner_class: RRunner

base_params:
    warningLevel: 2         #  tells R whether to show warnings or quit, etc.

    fullTzarExpOutputDirRootWithSlash: $$output_path$$

    envLayersSrcDir: "/Users/Bill/D/Data/MattsVicTestLandscape/MtBuffaloEnvVars_Originals/LowerLeft/"
    envLayersWorkingDirName: "InputEnvLayers"

    clusterFilePath: "/Users/Bill/D/Data/MattsVicTestLandscape/MtBuffaloSupervisedClusterLayers/LowerLeft/"


    asciiImgFileNameRoots:
        - "aniso_heat"
        - "evap_jan"
        - "evap_jul"
        - "insolation"
        - "max_temp"
        - "min_temp"
        - "modis_evi"
        - "modis_mir"
        - "ndmi"
        - "pottassium"
        - "raindays_jan"
        - "raindays_jul"
        - "rainfall_jan"
        - "rainfall_jul"
        - "thorium"
        - "twi_topocrop"
        - "vert_major"
        - "vert_minor"
        - "vert_saline"
        - "vis_sky"


    envLayerWeights:
        "aniso_heat": "randomIn0-1"
        "evap_jan": 0.5
        "evap_jul": 0.5
        "insolation": "randomIn0-1"
        "max_temp": 0.5
        "min_temp": 0.5
        "modis_evi": 0.5
        "modis_mir": 0.5
        "ndmi": 0.5
        "pottassium": "randomIn0-1"
        "raindays_jan": 0.5
        "raindays_jul": 0.5
        "rainfall_jan": 0.5
        "rainfall_jul": 0.5
        "thorium": "randomIn0-1"
        "twi_topocrop": "randomIn0-1"
        "vert_major": "randomIn0-1"
        "vert_minor": "randomIn0-1"
        "vert_saline": "randomIn0-1"
        "vis_sky": "randomIn0-1"


