project_name: g2
runner_class: RRunner

base_params:
    warningLevel: 2         #  tells R whether to show warnings or quit, etc.

    fullTzarExpOutputDirRootWithSlash: $$output_path$$

    envLayersSrcDir: "/Users/Bill/D/Data/MattsVicTestLandscape/MtBuffaloEnvVars_Originals/LowerLeft_r256c256/UpperRight_r128c128/"
    envLayersWorkingDirName: "InputEnvLayers"

    clusterFilePath: "/Users/Bill/D/Data/MattsVicTestLandscape/MtBuffaloSupervisedClusterLayers/LowerLeft_r256c256/UpperRight_r128c128/"

    smoothSuitabilitiesWithGaussian: TRUE
    gaussianSuitabilitySmoothingMean: 0
    gaussianSuitabilitySmoothingSD: 1

    scaleInputs: TRUE  #  DO NOT CHANGE THIS VALUE FOR NOW.  SEE COMMENT in original code.
    dataSrc: "mattData"    #  Should become a guppy option...

    numSpp: NA

    randomSeed: 17

    imgFileType: "asc"
    numNonEnvDataCols: 0

    clusterFileNameStem: "env_clusters"

    trueProbDistSppFilenameBase: "true.prob.dist.spp."

    trueProbDistFilePrefix: "true.prob.dist"

    useRandomNumTruePresForEachSpp: TRUE    #  variables$PAR.use.random.num.true.presences
    minTruePresFracOfLandscape: 0.0002    #  0.002    #  variables$PAR.min.true.presence.fraction.of.landscape
    maxTruePresFracOfLandscape: 0.002     #  0.2      # variables$PAR.max.true.presence.fraction.of.landscape
    numTruePresForEachSpp_string: "50,100,75"    #  variables$PAR.num.true.presences

    PARuseAllSamples: FALSE

    doMaxentReplicates: FALSE
    maxentReplicateType: "crossvalidate"
    numMaxentReplicates: 5

    numProcessors: 1
    verboseMaxent: TRUE

    maxentFullPathName: "/Users/Bill/D/rdv-framework/lib/maxent/maxent.jar"

    showRawErrorInDist: TRUE
    showAbsErrorInDist:  TRUE
    showPercentErrorInDist:  TRUE
    showAbsPercentErrorInDist:  TRUE
    showTruncatedPercentErrImg:  TRUE
    showHeatmap: FALSE

    useOldMaxentOutputForInput: FALSE
    writeToFile: FALSE
    useDrawImage: FALSE


    asciiImgFileNameRoots:
        - "aniso_heat"
        - "evap_jan"
        - "evap_jul"
        - "insolation"
        - "max_temp"
        - "min_temp"
        - "modis_evi"
        - "modis_mir"
        - "ndmi"
        - "pottassium"
        - "raindays_jan"
        - "raindays_jul"
        - "rainfall_jan"
        - "rainfall_jul"
        - "thorium"
        - "twi_topocrop"
        - "vert_major"
        - "vert_minor"
        - "vert_saline"
        - "vis_sky"


    envLayerWeights:
        "aniso_heat": "randomIn0-1"
        "evap_jan": 0.5
        "evap_jul": 0.5
        "insolation": "randomIn0-1"
        "max_temp": 0.5
        "min_temp": 0.5
        "modis_evi": 0.5
        "modis_mir": 0.5
        "ndmi": 0.5
        "pottassium": "randomIn0-1"
        "raindays_jan": 0.5
        "raindays_jul": 0.5
        "rainfall_jan": 0.5
        "rainfall_jul": 0.5
        "thorium": "randomIn0-1"
        "twi_topocrop": "randomIn0-1"
        "vert_major": "randomIn0-1"
        "vert_minor": "randomIn0-1"
        "vert_saline": "randomIn0-1"
        "vis_sky": "randomIn0-1"


