#===============================================================================

make.marxan.bound.dat.use.patches.as.planning.units <-
    function (PAR.Marxan2.input.dir,
              patch.attributes.file,
              current.planning.unit  #  temp idx in for loop
                    #  non.habitat.indicator  #  in ascelin's list but not used?
              )
        {
  # make.marxan.bound.dat.use.patches.as.planning.units <- function(PAR.marxan2.Input.Directory,
  #                                                                 patch.attributes.file,
  #                                                                 planning.units.filename,
  #                                                                 non.habitat.indicator
  # ){

      #e.g. make.marxan.bound.dat.use.patches.as.planning.units(PAR.marxan2.Input.Directory,                                                          patch.attributes.file,planning.units.filename,non.habitat.indicator                                                     )

      #-----------------------------------------------------------#
      #                                                           #
      #          make.marxan.patch.boundry.file.R                 #
      #                                                           #
      #  This creates the file 'bound.dat', needed for MARXAN.    #
      #  This takes care of the case where patchs are used as     #
      #  the planning units.  It gets info from the file          #
      #  binaryHabitatMap.patches.att, generated by Lucy's code   #
      #  It has the boundary length for each patch in it.         #
      #  This file specifies the the boundary of each planning    #
      #  unit (PU) and and shared boundries between each pair of  #
      #  planning units that have a common boundary.              #
      #  This assumes the planning units are rectangles and cover #
      #  the whole region.                                        #
      #                                                           #
      #  The format of the file is:                               #
      #  header "id1,id2,boundary"                                #
      #  then id1,id2,boundary                                    #
      #  where  id1 is PU 1 and id2 is PU 2 and is the boundary   #
      #  1,1,50  means planning unit 1 has a boundary of 50 units #
      #  1,2,25  means PU 1 and 2 have 25 units of shared boundary#
      #  Each boundary shuld only be mentioned once( eg shouldn't #
      #  have:                                                    #
      #  2,1,25                                                   #
      #                                                           #
      #  Created Oct  3, 2006 - Ascelin Gordon                    #
      #  source( '../R/make.marxan.patch.boundry.file.R' )        #
      #                                                           #
      #-----------------------------------------------------------#

      cat( '\nAbout to make bound.dat file for MARXAN' );
      cat( '\nmake.marxan.bound.dat.use.patches.as.planning.units\n')

      #file path to save bound.dat file
      bound.dat.File<-paste(PAR.Marxan2.input.dir, "bound.dat", sep="")

      # read in the pacth boundary lenths
      # this is a matrix generated by Lucy's java code
      # it has four columns <patch Id> <area> <perimiter. <smoothed perimiter>

      patch.attributes <- as.matrix ( read.table( patch.attributes.file ) );

      #Create header for new bound.dat file
      cat("id1,id2,boundary\n", file=bound.dat.File,append=FALSE)

      #Populate bound.dat file with information from   patch.attributes.file
      for(current.planning.unit in patch.attributes [,1]){
          cat(paste(patch.attributes[current.planning.unit,1],",",
                    patch.attributes[current.planning.unit,1],",",
                    patch.attributes[current.planning.unit,4],"\n", sep=""),
              file= bound.dat.File,append=TRUE)
      }

  # } #End make.marxan.bound.dat.use.patches.as.planning.units
}

#===============================================================================

